import { StyleSheet } from "react-native";

import { colors } from "../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  floatingHeader: { position: "absolute", top: 0, left: 0, right: 0, zIndex: 80, elevation: 24, backgroundColor: colors.bg },
  listContent: { paddingBottom: 116 },
  listContentWithHeader: { paddingTop: 72 },
  columns: { paddingHorizontal: 8 },
  feedFooter: { minHeight: 86, alignItems: "center", justifyContent: "center", gap: 8 },
  feedFooterText: { color: colors.muted, fontSize: 13, fontWeight: "900" },
  loading: { alignItems: "center", backgroundColor: "rgba(6,8,8,0.72)", bottom: 0, justifyContent: "center", left: 0, position: "absolute", right: 0, top: 0 },
  notificationRouteLoading: {
    alignItems: "center",
    backgroundColor: "rgba(6,8,8,0.92)",
    bottom: 0,
    gap: 14,
    justifyContent: "center",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 120,
  },
  notificationRouteLoadingText: { color: colors.text, fontSize: 15, fontWeight: "900" },
  errorText: { color: colors.danger, fontSize: 14, fontWeight: "800", lineHeight: 20, marginHorizontal: 18, marginTop: 14 },
  afterFilters: { height: 18 },
  homeSection: { marginTop: 2 },
  discoverHeading: { marginTop: 28, marginBottom: 10, paddingHorizontal: 18, gap: 12 },
  discoverHeadingActions: { flexDirection: "row", gap: 8 },
  discoverTitleCopy: { flex: 1, minWidth: 0 },
  kickerText: { color: colors.accent, letterSpacing: 3.5, fontSize: 11, fontWeight: "900", textTransform: "uppercase" },
  discoverTitle: { color: colors.text, fontSize: 44, lineHeight: 48, fontFamily: "serif", marginTop: 8 },
  forYouButton: { minHeight: 40, borderRadius: 14, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 7, backgroundColor: colors.panel },
  forYouText: { color: colors.text, fontSize: 13, fontWeight: "900" },
  inlineGrid: { flexDirection: "row", flexWrap: "wrap", paddingHorizontal: 8 },
  filterBar: { marginTop: 4, marginBottom: 10 },
  filterPills: { flexDirection: "row", flexWrap: "wrap", gap: 7, paddingHorizontal: 18, paddingVertical: 8, marginBottom: 8 },
  filterPill: { flexGrow: 1, flexBasis: "23%", minHeight: 36, borderRadius: 12, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 7, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 4, backgroundColor: colors.panel },
  filterPillActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  filterPillText: { color: colors.text, fontSize: 11, fontWeight: "900" },
  filterPillTextActive: { color: colors.text },
  mediaKindFilter: { height: 42, marginHorizontal: 18, marginTop: -1, marginBottom: 12, padding: 3, borderRadius: 13, backgroundColor: colors.panel, flexDirection: "row" },
  mediaKindFilterInline: { marginHorizontal: 0, marginTop: 14, marginBottom: 0 },
  mediaKindFilterOption: { flex: 1, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  mediaKindFilterOptionActive: { backgroundColor: colors.panel2 },
  mediaKindFilterOptionPressed: { opacity: .58 },
  mediaKindFilterText: { color: colors.muted, fontSize: 12, fontWeight: "900" },
  mediaKindFilterTextActive: { color: colors.text },
  calendarWrap: { marginTop: 2 },
  segmented: { flexDirection: "row", height: 44, marginHorizontal: 18, marginTop: 8, padding: 3, borderRadius: 14, backgroundColor: colors.panel },
  segment: { flex: 1, borderRadius: 11, alignItems: "center", justifyContent: "center" },
  segmentActive: { backgroundColor: colors.accent },
  segmentText: { color: colors.muted, fontSize: 13, fontWeight: "900" },
  segmentTextActive: { color: colors.text },
  calendarControlPressed: { opacity: .62 },
  calendarControlRow: { marginHorizontal: 18, marginTop: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  calendarViewSegmented: { height: 38, padding: 3, borderRadius: 12, backgroundColor: colors.panel, flexDirection: "row", flex: 1 },
  calendarViewSegment: { flex: 1, borderRadius: 9, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
  calendarViewSegmentActive: { backgroundColor: colors.panel2 },
  calendarViewText: { color: colors.muted, fontSize: 12, fontWeight: "900" },
  calendarViewTextActive: { color: colors.text },
  monthToolbar: { minHeight: 54, marginHorizontal: 18, marginTop: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  monthButton: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: colors.panel },
  monthTitle: { flex: 1, color: colors.text, fontFamily: "serif", fontSize: 27, fontWeight: "700", textAlign: "center" },
  calendarDisplayToggle: { height: 38, borderRadius: 12, backgroundColor: colors.panel, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 6 },
  calendarDisplayToggleActive: { backgroundColor: colors.accentSoft },
  calendarDisplayToggleText: { color: colors.muted, fontSize: 12, fontWeight: "900" },
  calendarDisplayToggleTextActive: { color: colors.text },
  recommendationIntro: { color: colors.muted, fontSize: 16, lineHeight: 24, marginHorizontal: 18, marginBottom: 8 },
  calendarGrid: { marginHorizontal: 18, marginTop: 4, paddingVertical: 10, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, flexDirection: "row", flexWrap: "wrap" },
  weekday: { width: "14.285%", color: colors.muted, textAlign: "center", fontSize: 10, fontWeight: "900", paddingBottom: 9 },
  dayCell: { width: "14.285%", minHeight: 48, borderRadius: 9, backgroundColor: "transparent", alignItems: "center", justifyContent: "flex-start", paddingTop: 5, borderWidth: 1, borderColor: "transparent" },
  dayCellPosterMode: { minHeight: 72 },
  blankDay: { backgroundColor: "transparent" },
  todayCell: { backgroundColor: "transparent" },
  dayHeading: { width: "100%", height: 26, alignItems: "center", justifyContent: "center" },
  dayHeadingWithCount: { paddingHorizontal: 3, flexDirection: "row", justifyContent: "space-between" },
  dayText: { width: 26, height: 26, borderRadius: 13, overflow: "hidden", color: colors.text, fontSize: 13, lineHeight: 26, fontWeight: "900", textAlign: "center" },
  todayText: { color: colors.text, backgroundColor: colors.accent },
  selectedDayCell: { borderColor: colors.line, backgroundColor: colors.panel },
  dayCount: { minWidth: 17, height: 17, paddingHorizontal: 3, borderRadius: 9, overflow: "hidden", backgroundColor: colors.accentSoft, color: colors.accent, textAlign: "center", lineHeight: 17, fontSize: 9, fontWeight: "900" },
  dayPosterStrip: { position: "absolute", left: 3, right: 3, bottom: 4, height: 28, flexDirection: "row", gap: 2, alignItems: "center" },
  dayPosterThumb: { flex: 1, height: 28, borderRadius: 3, overflow: "hidden", backgroundColor: colors.panel },
  dayPosterMore: { minWidth: 22, height: 22, borderRadius: 11, overflow: "hidden", backgroundColor: "rgba(0,0,0,0.72)", color: colors.text, textAlign: "center", lineHeight: 22, fontSize: 9, fontWeight: "900" },
  calendarWeekStrip: { marginHorizontal: 18, marginTop: 4, paddingVertical: 10, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, flexDirection: "row", gap: 3 },
  calendarWeekDay: { flex: 1, minWidth: 0, minHeight: 72, paddingVertical: 7, borderRadius: 10, borderWidth: 1, borderColor: "transparent", alignItems: "center", justifyContent: "center", gap: 3 },
  calendarWeekDayPosterMode: { minHeight: 108, paddingBottom: 39 },
  calendarWeekDayToday: { backgroundColor: colors.accentSoft },
  calendarWeekDaySelected: { borderColor: colors.line, backgroundColor: colors.panel },
  calendarWeekDayName: { color: colors.muted, fontSize: 10, fontWeight: "900", textTransform: "uppercase" },
  calendarWeekDayNumber: { color: colors.text, fontFamily: "serif", fontSize: 22, fontWeight: "700" },
  calendarWeekDayNumberToday: { color: colors.accent },
  calendarWeekDayCount: { minWidth: 20, height: 20, borderRadius: 10, overflow: "hidden", color: colors.muted, textAlign: "center", lineHeight: 20, fontSize: 10, fontWeight: "900" },
  calendarWeekDayCountActive: { backgroundColor: colors.accentSoft, color: colors.accent },
  calendarWeekPosterStrip: { position: "absolute", left: 4, right: 4, bottom: 5, height: 30, alignItems: "center", justifyContent: "center" },
  calendarWeekPosterThumb: { width: "100%", height: 30, borderRadius: 3, overflow: "hidden", backgroundColor: colors.panel2 },
  calendarWeekPosterMore: { position: "absolute", right: 2, bottom: 2, minWidth: 18, height: 18, paddingHorizontal: 3, borderRadius: 9, overflow: "hidden", backgroundColor: "rgba(0,0,0,0.78)", color: colors.text, textAlign: "center", lineHeight: 18, fontSize: 8, fontWeight: "900" },
  calendarWeekEmpty: { minHeight: 44, paddingHorizontal: 12, borderRadius: 10, color: colors.muted, backgroundColor: colors.panel, textAlignVertical: "center", fontSize: 12, fontWeight: "800" },
  agenda: { marginHorizontal: 18, marginTop: 18, gap: 20 },
  agendaDay: { gap: 6 },
  agendaHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  agendaDate: { color: colors.text, fontFamily: "serif", fontSize: 20, fontWeight: "700" },
  agendaCount: { minWidth: 24, height: 24, borderRadius: 12, backgroundColor: colors.accentSoft, color: colors.accent, textAlign: "center", lineHeight: 24, fontWeight: "900" },
  agendaRow: { minHeight: 68, borderRadius: 11, backgroundColor: colors.panel, padding: 7, flexDirection: "row", alignItems: "center", gap: 10 },
  agendaRowPressed: { opacity: .62, transform: [{ scale: .99 }] },
  agendaImage: { width: 72, height: 52, borderRadius: 6, overflow: "hidden", backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center" },
  agendaCopy: { flex: 1, minWidth: 0 },
  agendaTitle: { color: colors.text, fontSize: 15, fontWeight: "900" },
  agendaSub: { color: colors.muted, fontSize: 13, marginTop: 4 },
  profileStats: { marginTop: 10, marginHorizontal: 18, paddingTop: 10, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: colors.line, flexDirection: "row", flexWrap: "wrap", alignItems: "center" },
  profileStat: { width: "33.333%", minWidth: 0, minHeight: 70, paddingHorizontal: 2, paddingVertical: 4, alignItems: "center", justifyContent: "center", gap: 2 },
  profileStatPressed: { opacity: .55 },
  profileStatIcon: { width: 22, height: 20, alignItems: "center", justifyContent: "center" },
  profileStatCopy: { width: "100%", minWidth: 0, alignItems: "center" },
  profileStatValue: { width: "100%", color: colors.text, fontFamily: "serif", fontSize: 22, lineHeight: 24, fontWeight: "700", textAlign: "center" },
  profileStatLabel: { minHeight: 22, color: colors.muted, fontSize: 9, lineHeight: 11, fontWeight: "800", marginTop: 1, textAlign: "center" },
  profileDestinationTotal: { minHeight: 68, marginHorizontal: 18, marginBottom: 18, paddingVertical: 10, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, flexDirection: "row", alignItems: "center", gap: 10 },
  profileDestinationIcon: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.accentSoft, alignItems: "center", justifyContent: "center" },
  profileDestinationValue: { minWidth: 42, maxWidth: "44%", flexShrink: 1, color: colors.text, fontFamily: "serif", fontSize: 26, lineHeight: 29, fontWeight: "700", textAlign: "right" },
  profileDestinationCopy: { flex: 1, minWidth: 0 },
  profileDestinationLabel: { color: colors.text, fontSize: 13, fontWeight: "900" },
  profileDestinationDetail: { color: colors.muted, fontSize: 10, lineHeight: 14, fontWeight: "700", marginTop: 2 },
  profileNavOuter: { marginHorizontal: 18, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line },
  profileNav: { flexGrow: 1, paddingVertical: 10, paddingHorizontal: 0, alignItems: "center", justifyContent: "space-evenly" },
  profileNavPill: { flex: 1, minHeight: 30, paddingHorizontal: 4, alignItems: "center", justifyContent: "center" },
  profileNavPillActive: {},
  profileNavText: { color: colors.muted, fontSize: 12, fontWeight: "900" },
  profileNavTextActive: { color: colors.text },
  profileSection: { marginTop: 26 },
  profileHistorySection: { marginTop: -12 },
  notificationList: { gap: 10, paddingHorizontal: 18, paddingBottom: 120 },
  notificationClearButton: { alignSelf: "flex-end", minHeight: 36, marginRight: 18, marginTop: -4, marginBottom: 12, borderRadius: 18, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 6 },
  notificationClearText: { color: colors.muted, fontSize: 12, fontWeight: "900" },
  notificationCard: { minHeight: 92, borderWidth: 1, borderColor: colors.line, borderRadius: 16, backgroundColor: colors.panel, padding: 10, flexDirection: "row", alignItems: "center", gap: 12 },
  notificationCardUnread: { borderColor: colors.accent, backgroundColor: colors.accentSoft },
  notificationImage: { width: 86, height: 62, borderRadius: 10, backgroundColor: colors.panel2 },
  notificationIcon: { width: 50, height: 50, borderRadius: 25, backgroundColor: colors.accentSoft, alignItems: "center", justifyContent: "center" },
  notificationCopy: { flex: 1, minWidth: 0, gap: 3 },
  notificationTitle: { color: colors.text, fontSize: 15, fontWeight: "900" },
  notificationBody: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  notificationDate: { color: colors.muted, fontSize: 10, marginTop: 3 },
  historyGrid: { flexDirection: "row", flexWrap: "wrap", gap: 18, paddingHorizontal: 18 },
  historyCard: { width: "47%" },
  historyArt: { aspectRatio: 1.72, borderRadius: 12, overflow: "hidden", backgroundColor: colors.panel2 },
  historyRating: { position: "absolute", right: 8, top: 8, borderRadius: 16, overflow: "hidden", backgroundColor: "rgba(0,0,0,0.68)", color: colors.text, paddingHorizontal: 9, paddingVertical: 5, fontWeight: "900" },
  historyCardRewatch: { position: "absolute", right: 8, bottom: 8, minHeight: 25, borderRadius: 14, backgroundColor: "rgba(0,0,0,0.76)", paddingHorizontal: 7, flexDirection: "row", alignItems: "center", gap: 4 },
  historyCardRewatchText: { color: colors.accent, fontSize: 10, fontWeight: "900" },
  historyDate: { position: "absolute", left: 8, bottom: 8, borderRadius: 8, overflow: "hidden", backgroundColor: "rgba(0,0,0,0.7)", color: colors.text, paddingHorizontal: 8, paddingVertical: 4, fontWeight: "900" },
  historyTitle: { color: colors.text, fontSize: 16, fontWeight: "900", marginTop: 8 },
  historySub: { color: colors.muted, fontSize: 13, marginTop: 3 },
  historyTools: { marginHorizontal: 18, marginBottom: 18, gap: 12 },
  historySearchRow: { minHeight: 52, borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 9 },
  historySearchInput: { flex: 1, minWidth: 0, color: colors.text, fontSize: 15 },
  historySearchButton: { minWidth: 72, minHeight: 36, borderRadius: 12, backgroundColor: colors.accent, paddingHorizontal: 13, alignItems: "center", justifyContent: "center" },
  historySearchButtonBusy: { opacity: 0.82 },
  historySearchButtonText: { color: colors.text, fontSize: 12, fontWeight: "900" },
  historyFilterRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  historyFilterPill: { flexGrow: 1, flexBasis: "30%", minWidth: 92, minHeight: 42, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, alignItems: "center", justifyContent: "center", paddingHorizontal: 8 },
  historyFilterPillActive: { borderColor: colors.accent, backgroundColor: colors.accentSoft },
  historyFilterText: { color: colors.muted, fontSize: 13, fontWeight: "900" },
  historyFilterTextActive: { color: colors.text },
  historySummary: { marginHorizontal: 18, marginBottom: 22, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, flexDirection: "row" },
  historySummaryCell: { flex: 1, minHeight: 72, paddingVertical: 12, paddingHorizontal: 10, borderRightWidth: 1, borderColor: colors.line, justifyContent: "center", gap: 4 },
  historySummaryCellLast: { borderRightWidth: 0 },
  historySummaryValue: { color: colors.text, fontFamily: "serif", fontSize: 28, fontWeight: "700" },
  historySummaryLabel: { color: colors.muted, fontSize: 11, fontWeight: "800" },
  historyTimeline: { gap: 26, paddingHorizontal: 18 },
  historyPager: { marginHorizontal: 18, marginTop: 24, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 12 },
  historyPageButton: { minWidth: 108, minHeight: 44, borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 },
  historyPageButtonDisabled: { opacity: 0.35 },
  historyPageButtonText: { color: colors.text, fontSize: 14, fontWeight: "900" },
  historyPageLabel: { color: colors.muted, fontSize: 12, fontWeight: "900" },
  historyInlineLoading: { minHeight: 120, alignItems: "center", justifyContent: "center", gap: 10 },
  historyInlineLoadingText: { color: colors.muted, fontSize: 13, fontWeight: "800" },
  historyLoadMore: { minHeight: 48, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, alignItems: "center", justifyContent: "center" },
  historyLoadMoreText: { color: colors.text, fontSize: 14, fontWeight: "900" },
  historyDay: { gap: 10 },
  historyDayDate: { gap: 2 },
  historyDayTitle: { color: colors.text, fontSize: 18, fontWeight: "900" },
  historyDaySub: { color: colors.muted, fontSize: 12, fontWeight: "700" },
  historyEventList: { gap: 9 },
  historyEvent: { minHeight: 96, borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: colors.panel, padding: 8, flexDirection: "row", alignItems: "center", gap: 12 },
  historyEventArt: { width: 96, height: 62, borderRadius: 9, overflow: "hidden", backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center" },
  historyEventCopy: { flex: 1, minWidth: 0, gap: 3 },
  historyEventKicker: { color: colors.accent, letterSpacing: 1.8, fontSize: 10, fontWeight: "900", textTransform: "uppercase" },
  historyEventTitle: { color: colors.text, fontSize: 15, fontWeight: "900" },
  historyEventSubtitle: { color: colors.muted, fontSize: 12, fontWeight: "700" },
  historyEventMeta: { minWidth: 54, alignItems: "flex-end", gap: 5 },
  historyMetaInline: { flexDirection: "row", alignItems: "center", gap: 4 },
  historyRewatch: { color: colors.accent, fontSize: 10, fontWeight: "900" },
  historyEventTime: { color: colors.muted, fontSize: 11, fontWeight: "700" },
  historyRemoveButton: { width: 28, height: 28, borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,77,77,0.28)", alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,77,77,0.08)" },
  historyRatingSmall: { fontSize: 10 },
  progressGroups: { marginHorizontal: 18, borderTopWidth: 2, borderColor: colors.accent, flexDirection: "row", gap: 12, paddingTop: 18 },
  progressGroup: { flex: 1, minHeight: 116 },
  progressCount: { color: colors.text, fontFamily: "serif", fontSize: 34, fontWeight: "700" },
  progressLabel: { color: colors.muted, fontSize: 13, marginTop: 4 },
  miniPosters: { flexDirection: "row", marginTop: 10 },
  miniPoster: { width: 34, height: 50, borderRadius: 5, marginRight: -9, borderWidth: 1, borderColor: colors.bg },
  streakRow: { marginHorizontal: 18, marginTop: 18, paddingTop: 20, borderTopWidth: 1, borderTopColor: colors.line, flexDirection: "row", alignItems: "center", gap: 16 },
  streakLabel: { color: colors.muted, fontSize: 14 },
  streakValue: { color: colors.text, fontFamily: "serif", fontSize: 32, fontWeight: "700" },
  streakMeta: { color: colors.muted, fontSize: 13 },
  profileSubhead: { marginHorizontal: 18, marginTop: 24, marginBottom: 10, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  profileSubheadTitle: { color: colors.text, fontSize: 18, fontWeight: "900" },
  profileSubheadAction: { color: colors.muted, fontWeight: "900" },
  statisticsGrid: { marginHorizontal: 18, borderTopWidth: 1, borderLeftWidth: 1, borderColor: colors.line, flexDirection: "row", flexWrap: "wrap" },
  statisticsCard: { width: "50%", minHeight: 122, borderRightWidth: 1, borderBottomWidth: 1, borderColor: colors.line, padding: 18, justifyContent: "center" },
  statisticsValue: { color: colors.text, fontFamily: "serif", fontSize: 36, lineHeight: 42 },
  statisticsLabel: { color: colors.muted, fontSize: 15, fontWeight: "800", marginTop: 4 },
  statsSectionHead: { marginTop: 34, marginHorizontal: 18 },
  statsSectionTitle: { color: colors.text, fontFamily: "serif", fontSize: 38, lineHeight: 44, marginTop: 6 },
  genreStatsPanel: { marginTop: 18, marginHorizontal: 18, borderWidth: 1, borderColor: colors.line, borderRadius: 16, backgroundColor: colors.panel, padding: 16, gap: 13 },
  genreLegend: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginBottom: 4 },
  genreLegendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  genreLegendDot: { width: 8, height: 8, borderRadius: 4 },
  genreLegendText: { color: colors.muted, fontSize: 11, fontWeight: "800", textTransform: "capitalize" },
  genreStatRow: { minHeight: 42, borderRadius: 10, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 8 },
  genreStatRowActive: { backgroundColor: colors.panel2 },
  genreStatName: { width: 92, color: colors.text, fontSize: 13, fontWeight: "900" },
  genreStatBar: { flex: 1, height: 12, borderRadius: 8, backgroundColor: colors.panel2, overflow: "hidden" },
  genreStatFill: { height: "100%", flexDirection: "row", borderRadius: 8, overflow: "hidden" },
  genreStatTotal: { width: 26, color: colors.muted, textAlign: "right", fontSize: 16, fontWeight: "800" },
  genreShelf: { marginTop: 16 },
  reviewList: { marginHorizontal: 18, borderTopWidth: 1, borderTopColor: colors.line },
  reviewRow: { paddingVertical: 18, borderBottomWidth: 1, borderBottomColor: colors.line },
  reviewTargetRow: { minHeight: 68, flexDirection: "row", alignItems: "flex-start", gap: 12, borderRadius: 10 },
  reviewTargetRowPressed: { opacity: .58 },
  reviewImage: { width: 92, height: 68, borderRadius: 10, backgroundColor: colors.panel2 },
  reviewTargetCopy: { flex: 1, minWidth: 0 },
  reviewCopy: { minWidth: 0, marginLeft: 104 },
  reviewKindRow: { flexDirection: "row", alignItems: "center", gap: 12, flexWrap: "wrap" },
  reviewPrivateBadge: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 7, height: 22, borderRadius: 11, backgroundColor: colors.panel2 },
  reviewPrivateText: { color: colors.muted, fontSize: 10, fontWeight: "900" },
  reviewKind: { color: colors.accent, fontSize: 12, fontWeight: "900", letterSpacing: 1.3, textTransform: "uppercase" },
  reviewScore: { flexDirection: "row", alignItems: "center", gap: 4 },
  reviewScoreText: { color: "#ffc24b", fontSize: 12, fontWeight: "900" },
  reviewMedia: { color: colors.text, fontSize: 17, fontWeight: "900", marginTop: 4 },
  reviewMeta: { color: colors.muted, fontSize: 13, marginTop: 4 },
  reviewTitle: { color: colors.text, fontFamily: "serif", fontSize: 19, fontWeight: "700", marginTop: 6 },
  reviewBody: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 5 },
  reviewBodyMeasure: { position: "absolute", left: 0, right: 0, top: 0, opacity: 0 },
  reviewExpand: { color: colors.accent, fontSize: 12, fontWeight: "800", marginTop: 7 },
  groupControls: { marginHorizontal: 18, marginTop: 6, marginBottom: 18, flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
  groupLabel: { color: colors.muted, fontSize: 13, fontWeight: "900", marginRight: 2 },
  groupChip: { minHeight: 36, borderRadius: 18, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, backgroundColor: colors.panel },
  groupChipActive: { borderColor: colors.accent, backgroundColor: colors.accentSoft },
  groupChipText: { color: colors.muted, fontSize: 13, fontWeight: "900" },
  groupChipTextActive: { color: colors.text },
  listGroupBlock: { marginBottom: 14 },
  listGroupTitle: { color: colors.accent, fontSize: 12, fontWeight: "900", letterSpacing: 2, textTransform: "uppercase", marginHorizontal: 18, marginBottom: 12 },
  listGrid: { flexDirection: "row", flexWrap: "wrap", gap: 18, paddingHorizontal: 18 },
  listCard: { width: "47%", minHeight: 250 },
  posterStack: { height: 130, borderRadius: 14, backgroundColor: colors.panel, overflow: "hidden", alignItems: "center", justifyContent: "center" },
  stackPoster: { position: "absolute", top: 18, width: 76, height: 108, borderRadius: 8 },
  listVisibility: { color: colors.accent, fontSize: 12, fontWeight: "900", letterSpacing: 2, textTransform: "uppercase", marginTop: 14 },
  listName: { color: colors.text, fontSize: 20, fontWeight: "900", marginTop: 8 },
  listDescription: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 8 },
  listCount: { color: colors.text, fontSize: 14, fontWeight: "900", marginTop: 22 },
  shortcuts: { marginHorizontal: 18, marginTop: 34, borderTopWidth: 1, borderTopColor: colors.line },
  shortcut: { minHeight: 80, flexDirection: "row", alignItems: "center", gap: 16, borderBottomWidth: 1, borderBottomColor: colors.line },
  shortcutTitle: { color: colors.text, fontSize: 18, fontWeight: "900" },
  shortcutBody: { color: colors.muted, fontSize: 14, marginTop: 3 },
  railBlock: { marginBottom: 2 },
  railContent: { gap: 14, paddingHorizontal: 18, paddingBottom: 6 },
  railCard: { width: 138 },
  railPoster: { aspectRatio: 0.68, borderRadius: 16, overflow: "hidden", backgroundColor: colors.panel2 },
  posterImage: { width: "100%", height: "100%" },
  posterFallback: { color: colors.muted, textAlign: "center", padding: 14, fontSize: 15, fontWeight: "800" },
  railRating: { position: "absolute", top: 8, right: 8, borderRadius: 14, backgroundColor: "rgba(0,0,0,0.66)", paddingHorizontal: 8, paddingVertical: 5 },
  railRatingText: { color: colors.text, fontSize: 11, fontWeight: "900" },
  railTitle: { color: colors.text, fontSize: 15, fontWeight: "900", marginTop: 8 },
  railMeta: { color: colors.muted, fontSize: 12, marginTop: 3 },
  profileHero: { minHeight: 488, marginTop: 0, backgroundColor: colors.bg, overflow: "hidden" },
  profileBanner: { position: "absolute", left: 0, right: 0, top: 0, height: 230 },
  profileBannerFallback: { position: "absolute", left: 0, right: 0, top: 0, height: 230, backgroundColor: colors.panel2 },
  profileShade: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(0,0,0,0.52)" },
  profileContent: { flex: 1, justifyContent: "flex-end", padding: 22, paddingTop: 178 },
  profileAvatarLarge: { width: 94, height: 94, borderRadius: 47, borderWidth: 3, borderColor: colors.bg, backgroundColor: "#008f82", alignItems: "center", justifyContent: "center", overflow: "hidden", marginBottom: 14 },
  profileAvatarImage: { width: "100%", height: "100%" },
  profileAvatarInitial: { color: colors.text, fontSize: 42, fontWeight: "900" },
  profileNameRow: { flexDirection: "row", alignItems: "flex-end", gap: 12 },
  profileNameCopy: { flex: 1, minWidth: 0 },
  profileKicker: { color: colors.accent, fontSize: 11, fontWeight: "900", letterSpacing: 2.4, textTransform: "uppercase" },
  profileName: { color: colors.text, fontFamily: "serif", fontSize: 34, lineHeight: 38, marginTop: 5 },
  profileHandle: { color: colors.muted, fontSize: 15, fontWeight: "800", marginTop: 4 },
  signOutButton: { borderRadius: 18, borderWidth: 1, borderColor: "rgba(255,255,255,0.18)", backgroundColor: "rgba(0,0,0,0.34)", paddingHorizontal: 14, paddingVertical: 10 },
  signOutText: { color: colors.text, fontWeight: "900" },
  profileBio: { color: colors.text, fontSize: 15, lineHeight: 22, marginTop: 14 },
  profileRegion: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 11 },
  profileRegionText: { color: colors.muted, fontSize: 13, fontWeight: "800" },
  editProfileButton: { minHeight: 54, borderRadius: 28, borderWidth: 1, borderColor: colors.line, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 18, backgroundColor: "rgba(10,13,14,0.76)" },
  editProfileText: { color: colors.text, fontSize: 17, fontWeight: "900" },
  mfaPanel: { marginHorizontal: 18, marginTop: 16, padding: 22, borderColor: colors.line, borderRadius: 24, borderWidth: 1, backgroundColor: colors.panel },
  mfaIcon: { width: 70, height: 70, borderRadius: 35, backgroundColor: colors.accentSoft, alignItems: "center", justifyContent: "center", marginBottom: 16 },
  mfaTitle: { color: colors.text, fontSize: 28, fontWeight: "900" },
  mfaBody: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 8 },
  mfaInput: { height: 64, borderRadius: 18, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 16, color: colors.text, fontSize: 27, fontWeight: "900", letterSpacing: 8, textAlign: "center", backgroundColor: colors.panel2, marginTop: 16 },
  mfaError: { color: colors.danger, fontSize: 14, fontWeight: "800", lineHeight: 20, marginTop: 12 },
  authPanel: { marginHorizontal: 18, marginTop: 16, padding: 20, borderColor: colors.line, borderRadius: 24, borderWidth: 1, backgroundColor: colors.panel },
  authTitle: { color: colors.text, fontSize: 28, fontWeight: "900" },
  authBody: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 8, marginBottom: 16 },
  googleButton: { height: 56, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: "#f6f2eb", marginBottom: 12 },
  googleButtonText: { color: "#101415", fontSize: 17, fontWeight: "900" },
  authDivider: { color: colors.muted, textAlign: "center", fontSize: 13, fontWeight: "800", marginBottom: 2 },
  authInput: { height: 58, borderRadius: 16, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 16, color: colors.text, fontSize: 17, backgroundColor: colors.panel2, marginTop: 10 },
  authButton: { height: 58, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: colors.accent, marginTop: 14 },
  disabledButton: { opacity: 0.7 },
  authButtonText: { color: colors.text, fontSize: 17, fontWeight: "900" },
  switchAuth: { alignItems: "center", paddingTop: 16 },
  switchAuthText: { color: colors.muted, fontSize: 14, fontWeight: "800" },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginHorizontal: 18, marginTop: 16 },
  statCard: { flexBasis: "47%", flexGrow: 1, minHeight: 96, borderRadius: 20, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, padding: 15 },
  statValue: { color: colors.text, fontSize: 27, fontWeight: "900", marginTop: 8 },
  statLabel: { color: colors.muted, fontSize: 13, fontWeight: "800", marginTop: 3 },
  emptyPanel: { marginHorizontal: 18, marginTop: 20, padding: 22, borderColor: colors.line, borderRadius: 24, borderWidth: 1, backgroundColor: colors.panel },
  emptyTitle: { color: colors.text, fontSize: 26, fontWeight: "900" },
  emptyBody: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 8 },
  emptyAction: { alignSelf: "flex-start", marginTop: 16, borderRadius: 18, backgroundColor: colors.accent, paddingHorizontal: 16, paddingVertical: 11 },
  emptyActionText: { color: colors.text, fontWeight: "900" },
  detailContent: { paddingBottom: 126 },
  detailHero: { minHeight: 500, overflow: "hidden", justifyContent: "flex-end", backgroundColor: colors.panel },
  detailShade: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(0,0,0,0.56)" },
  backButton: { position: "absolute", top: 18, left: 18, zIndex: 2, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 20, backgroundColor: "rgba(0,0,0,0.48)", flexDirection: "row", alignItems: "center", gap: 4 },
  backText: { color: colors.text, fontSize: 15, fontWeight: "900" },
  detailCopy: { flexDirection: "row", alignItems: "flex-end", padding: 20, gap: 16 },
  detailPoster: { width: 116, height: 172, borderRadius: 16, backgroundColor: colors.panel2 },
  detailText: { flex: 1, minWidth: 0 },
  detailKicker: { color: colors.accent, letterSpacing: 3, fontSize: 12, fontWeight: "900", textTransform: "uppercase" },
  detailTitle: { color: colors.text, fontFamily: "serif", fontSize: 36, lineHeight: 40, marginTop: 8 },
  detailMeta: { color: colors.text, fontSize: 14, fontWeight: "800", marginTop: 8 },
  detailBody: { padding: 18 },
  detailOverview: { color: colors.text, fontSize: 18, lineHeight: 28 },
  detailActionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 22 },
  detailAction: { flexBasis: "47%", flexGrow: 1, minHeight: 56, borderRadius: 17, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  detailActionText: { color: colors.text, fontSize: 15, fontWeight: "900" },
  detailDanger: { minHeight: 56, borderRadius: 17, borderWidth: 1, borderColor: "rgba(255,77,77,0.35)", backgroundColor: "rgba(255,77,77,0.1)", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 10 },
  detailDangerText: { color: colors.danger, fontSize: 15, fontWeight: "900" },
  factGrid: { borderTopWidth: 1, borderTopColor: colors.line, marginTop: 22 },
  fact: { paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: colors.line },
  factLabel: { color: colors.muted, fontSize: 13, fontWeight: "800" },
  factValue: { color: colors.text, fontSize: 17, fontWeight: "900", marginTop: 5 },
  searchPanel: { marginHorizontal: 18, marginTop: 4, marginBottom: 18, gap: 12 },
  searchResultsLoading: { minHeight: 140, marginHorizontal: 18, borderRadius: 18, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, alignItems: "center", justifyContent: "center", gap: 10 },
  searchResultsLoadingText: { color: colors.muted, fontSize: 14, fontWeight: "800" },
  lastWatchedText: { color: colors.muted, fontSize: 13, fontWeight: "800", lineHeight: 19, marginTop: 10, marginBottom: 14 },
  movieWatchedSummary: { minHeight: 62, marginBottom: 12, paddingHorizontal: 14, paddingVertical: 11, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, flexDirection: "row", alignItems: "center", gap: 11 },
  movieWatchedSummaryCopy: { flex: 1, minWidth: 0 },
  movieWatchedSummaryTitle: { color: colors.text, fontSize: 15, fontWeight: "900" },
  movieWatchedSummaryMeta: { color: colors.muted, fontSize: 12, fontWeight: "800", marginTop: 3 },
  searchBox: { minHeight: 60, borderRadius: 18, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 14 },
  searchInput: { flex: 1, color: colors.text, fontSize: 18 },
  searchClearButton: { minHeight: 38, borderRadius: 19, flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 4 },
  searchClearText: { color: colors.muted, fontSize: 12, fontWeight: "900" },
  searchButton: { height: 58, borderRadius: 20, backgroundColor: colors.accent, alignItems: "center", justifyContent: "center" },
  searchButtonText: { color: colors.text, fontSize: 18, fontWeight: "900" },
  listDetailHeader: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 20 },
  backChip: { alignSelf: "flex-start", minHeight: 40, borderRadius: 20, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 12 },
  backChipText: { color: colors.text, fontWeight: "900" },
  listDetailTitle: { color: colors.text, fontFamily: "serif", fontSize: 46, lineHeight: 50, marginTop: 12 },
  listDetailBody: { color: colors.muted, fontSize: 16, lineHeight: 24, marginTop: 8 },
  listDetailTools: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 18 },
  modalScrim: { flex: 1, backgroundColor: "rgba(0,0,0,0.56)" },
  modalKeyboardAvoider: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0, justifyContent: "flex-end" },
  actionSheet: { position: "absolute", left: 14, right: 14, bottom: 18, maxHeight: "92%", borderRadius: 28, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, padding: 18 },
  grabber: { width: 44, height: 5, borderRadius: 3, backgroundColor: "#4a5052", alignSelf: "center", marginBottom: 10 },
  actionHeader: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  actionThumb: { width: 48, height: 66, borderRadius: 8, backgroundColor: colors.panel2 },
  actionTitle: { color: colors.text, fontSize: 22, fontWeight: "900" },
  actionSub: { color: colors.muted, marginTop: 4, marginBottom: 10, fontSize: 14 },
  watchingRemovePanel: { marginVertical: 8, borderWidth: 1, borderColor: "rgba(255,91,62,.30)", borderRadius: 15, backgroundColor: "rgba(255,91,62,.08)", overflow: "hidden" },
  watchingRemoveAction: { minHeight: 72, paddingHorizontal: 12, paddingVertical: 10, flexDirection: "row", alignItems: "center", gap: 10 },
  watchingRemoveIcon: { width: 30, alignItems: "center", justifyContent: "center" },
  watchingRemoveCopy: { flex: 1, minWidth: 0, justifyContent: "center" },
  watchingRemoveText: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "900" },
  watchingRemoveSub: { color: colors.muted, marginTop: 3, fontSize: 12, lineHeight: 16 },
  closeButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center" },
  actionRow: { minHeight: 52, flexDirection: "row", alignItems: "center", borderRadius: 14, paddingHorizontal: 8 },
  actionIcon: { width: 38 },
  actionText: { color: colors.text, fontSize: 17, fontWeight: "800" },
  dangerText: { color: colors.danger },
  actionDivider: { height: 1, backgroundColor: colors.line, marginVertical: 8 },
  actionSectionLabel: { color: colors.accent, fontSize: 11, fontWeight: "900", letterSpacing: 2.2, textTransform: "uppercase", marginBottom: 8 },
  contextPrimaryActions: { flexDirection: "row", gap: 10, marginTop: 10, marginBottom: 8 },
  contextPrimaryButton: { flex: 1, minHeight: 76, borderRadius: 14, backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center", gap: 6, paddingHorizontal: 4 },
  contextPrimaryText: { color: colors.text, fontSize: 12, fontWeight: "900", textAlign: "center" },
  contextListSearch: { height: 54, borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel2, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 14, marginBottom: 10 },
  contextListInput: { flex: 1, color: colors.text, fontSize: 15 },
  actionListScroll: { maxHeight: 330 },
  actionListScrollCompact: { maxHeight: 220 },
  actionListContent: { paddingBottom: 10, gap: 4 },
  listRetryButton: { minHeight: 48, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.line, borderRadius: 12 },
  statusSheetRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginVertical: 10 },
  statusSheetButton: { flexBasis: "31%", minHeight: 58, borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center", gap: 4 },
  statusSheetButtonActive: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
  statusSheetText: { color: colors.muted, fontSize: 11, fontWeight: "900" },
  statusSheetTextActive: { color: colors.text },
  listActionRow: { minHeight: 56, borderRadius: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 14 },
  listActionRowActive: { backgroundColor: colors.panel2 },
  listActionName: { color: colors.text, fontSize: 15, fontWeight: "800", flex: 1 },
  listActionNameActive: { color: "#6ee7a8" },
  listActionState: { flexDirection: "row", alignItems: "center", gap: 5 },
  listActionText: { color: colors.muted, fontSize: 13, fontWeight: "900" },
  listActionTextActive: { color: "#6ee7a8" },
  currentListSection: { borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, marginTop: 12, marginBottom: 12, paddingTop: 14, paddingBottom: 14 },
  franchiseGroupChips: { gap: 8, paddingBottom: 8 },
  franchiseGroupCreateRow: { flexDirection: "row", gap: 8 },
  franchiseGroupInput: { flex: 1, minHeight: 46, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel2, color: colors.text, paddingHorizontal: 12, fontSize: 15, fontWeight: "700" },
  franchiseGroupSave: { minHeight: 46, borderRadius: 14, backgroundColor: colors.accent, alignItems: "center", justifyContent: "center", paddingHorizontal: 18 },
  franchiseGroupSaveText: { color: colors.text, fontSize: 14, fontWeight: "900" },
  currentListRemove: { minHeight: 54, borderRadius: 16, backgroundColor: "rgba(255,77,77,0.12)", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  currentListRemoveText: { color: "#ff8585", fontSize: 15, fontWeight: "900" },
  watchLogScroll: { flexShrink: 1 },
  watchLogScrollContent: { paddingBottom: 12 },
  watchLogSave: { flexShrink: 0, marginTop: 12 },
  episodeHero: { minHeight: 640, backgroundColor: colors.panel, justifyContent: "flex-end", overflow: "hidden" },
  entityHeader: { padding: 18, paddingBottom: 4 },
  entityHeroRow: { flexDirection: "row", gap: 16, alignItems: "center", marginTop: 18 },
  entityPortrait: { width: 118, height: 164, borderRadius: 18, overflow: "hidden", backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center" },
  entityLogoBox: { width: 132, height: 88, borderRadius: 16, overflow: "hidden", backgroundColor: "#eeeae2", alignItems: "center", justifyContent: "center" },
  entityCopy: { flex: 1, minWidth: 0 },
  entityTitle: { color: colors.text, fontFamily: "serif", fontSize: 38, lineHeight: 42, marginTop: 6 },
  entitySubtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 8 },
  entityLoadMore: { minHeight: 70, alignItems: "center", justifyContent: "center", paddingBottom: 18 },
  entityLoadMoreText: { color: colors.muted, fontSize: 13, fontWeight: "800" },
  detailLoadingScreen: { flex: 1, minHeight: 760, backgroundColor: colors.bg, justifyContent: "center", overflow: "hidden", paddingHorizontal: 22 },
  detailLoadingCard: { borderRadius: 26, borderWidth: 1, borderColor: colors.line, backgroundColor: "rgba(13,17,17,0.86)", alignItems: "center", gap: 10, paddingHorizontal: 24, paddingVertical: 30 },
  detailLoadingTitle: { color: colors.text, fontFamily: "serif", fontSize: 30, fontWeight: "700", marginTop: 6, textAlign: "center" },
  detailLoadingText: { color: colors.muted, fontSize: 14, fontWeight: "800", lineHeight: 20, textAlign: "center" },
  detailHeroV2: { minHeight: 760, backgroundColor: colors.panel, justifyContent: "flex-end", overflow: "hidden" },
  detailShadeV2: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(0,0,0,0.48)" },
  detailHeroCopyV2: { padding: 22, paddingTop: 150 },
  detailPosterV2: { width: 106, height: 158, borderRadius: 14, backgroundColor: colors.panel2, marginBottom: 18 },
  detailTitleV2: { color: colors.text, fontFamily: "serif", fontSize: 46, lineHeight: 48, marginTop: 8 },
  ratingSourceRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 18 },
  ratingSource: { minWidth: 112, borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.18)", backgroundColor: "rgba(0,0,0,0.34)", padding: 12 },
  ratingSourceLoading: { borderColor: "rgba(255,84,57,0.32)", backgroundColor: "rgba(0,0,0,0.24)" },
  ratingSourceLabel: { color: colors.muted, fontSize: 11, fontWeight: "900", letterSpacing: 1.4, textTransform: "uppercase" },
  ratingSourceValue: { color: colors.text, fontSize: 20, fontWeight: "900", marginTop: 0 },
  ratingSourceValueRow: { minHeight: 28, flexDirection: "row", alignItems: "center", gap: 8, marginTop: 4 },
  ratingSourceValueLoading: { color: colors.muted, fontSize: 16, marginTop: 0 },
  detailTagline: { color: colors.text, fontFamily: "serif", fontSize: 24, fontStyle: "italic", lineHeight: 32, marginTop: 24 },
  trailerButton: { alignSelf: "flex-start", marginTop: 22, height: 58, borderRadius: 26, backgroundColor: colors.accent, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 20 },
  trailerButtonText: { color: colors.text, fontSize: 17, fontWeight: "900" },
  titleActionDock: { borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, paddingTop: 15, paddingBottom: 14, marginBottom: 22 },
  actionLabelBig: { color: colors.text, fontSize: 14, fontWeight: "900", letterSpacing: 1.8, textTransform: "uppercase", marginBottom: 12 },
  statusActions: { flexDirection: "row", gap: 3 },
  seriesProgressCard: { minHeight: 58, marginBottom: 10, paddingHorizontal: 13, paddingVertical: 10, borderRadius: 13, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, flexDirection: "row", alignItems: "center", gap: 11 },
  seriesProgressCardRewatching: { borderColor: "rgba(255,84,57,0.48)", backgroundColor: colors.accentSoft },
  seriesProgressCopy: { flex: 1, minWidth: 0, gap: 2 },
  seriesProgressTitle: { color: colors.text, fontSize: 14, fontWeight: "900" },
  seriesProgressMeta: { color: colors.muted, fontSize: 11, fontWeight: "800" },
  detailStatusButton: { flex: 1, minHeight: 46, borderRadius: 8, alignItems: "center", justifyContent: "center", gap: 3, backgroundColor: "transparent", position: "relative" },
  detailStatusButtonActive: { backgroundColor: colors.accentSoft, borderBottomWidth: 2, borderBottomColor: colors.accent },
  detailStatusText: { color: colors.muted, fontSize: 10, fontWeight: "900", textAlign: "center" },
  detailStatusTextActive: { color: colors.text },
  ratingAction: { minHeight: 66, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, marginTop: 15, paddingVertical: 10, flexDirection: "row", alignItems: "center", gap: 12 },
  ratingActionCopy: { flex: 1, minWidth: 0 },
  ratingActionLabel: { color: colors.muted, fontSize: 12, fontWeight: "900", letterSpacing: 1.4, textTransform: "uppercase" },
  ratingActionValue: { color: colors.text, fontFamily: "serif", fontSize: 27, fontWeight: "700", marginTop: 3 },
  detailQuickActions: { flexDirection: "row", flexWrap: "wrap", gap: 18, marginTop: 14 },
  quickAction: { minHeight: 40, borderRadius: 8, flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "transparent" },
  quickActionText: { color: colors.text, fontSize: 14, fontWeight: "900", flexShrink: 1 },
  detailLists: { marginTop: 12 },
  addToListButton: { minHeight: 50, borderRadius: 12, backgroundColor: colors.panel, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingHorizontal: 14, marginBottom: 8 },
  addToListText: { color: colors.text, fontSize: 15, fontWeight: "900", flex: 1 },
  listPickerSheet: { position: "absolute", left: 14, right: 14, bottom: 18, maxHeight: "88%", borderRadius: 28, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, padding: 16 },
  sheetHeaderRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  sheetTitleText: { color: colors.text, fontFamily: "serif", fontSize: 30, lineHeight: 34 },
  sheetSubText: { color: colors.muted, fontSize: 13, fontWeight: "800", marginTop: 3 },
  sheetCloseButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center" },
  listPickerSearch: { height: 50, borderRadius: 15, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel2, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 12, marginTop: 14 },
  listPickerInput: { flex: 1, color: colors.text, fontSize: 16 },
  listPickerScroll: { marginTop: 10, maxHeight: 430 },
  listPickerContent: { paddingBottom: 10, gap: 8 },
  detailListSheetRow: { minHeight: 58, borderRadius: 16, borderWidth: 1, borderColor: colors.line, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 14 },
  emptyMiniText: { color: colors.muted, fontSize: 14, fontWeight: "800", textAlign: "center", paddingVertical: 22 },
  detailListRow: { minHeight: 52, borderRadius: 14, borderWidth: 1, borderColor: colors.line, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 12, marginBottom: 8 },
  detailListRowActive: { backgroundColor: colors.panel2, borderColor: colors.accent },
  detailListName: { color: colors.text, fontSize: 15, fontWeight: "900", flex: 1 },
  detailListState: { color: colors.muted, fontSize: 13, fontWeight: "900" },
  detailListStateActive: { color: colors.accent },
  ratingSheet: { position: "absolute", left: 14, right: 14, bottom: 92, borderRadius: 26, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, padding: 16 },
  watchLogSheet: { position: "absolute", left: 14, right: 14, bottom: 18, maxHeight: "86%", borderRadius: 28, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, padding: 16 },
  watchQuickGrid: { flexDirection: "row", gap: 8, marginTop: 10 },
  watchQuickButton: { flex: 1, minHeight: 92, borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel2, padding: 10, justifyContent: "center", gap: 4 },
  watchQuickTitle: { color: colors.text, fontSize: 13, fontWeight: "900" },
  watchQuickSub: { color: colors.muted, fontSize: 11, fontWeight: "700" },
  watchCustomBox: { marginTop: 14, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 12 },
  watchInputsRow: { flexDirection: "row", gap: 8, marginTop: 8 },
  watchInput: { flex: 1, marginTop: 0 },
  watchTimeInput: { width: 98, marginTop: 0 },
  timePointRow: { flexDirection: "row", gap: 8, marginTop: 10 },
  timePointButton: { flex: 1, minHeight: 44, borderRadius: 14, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center", backgroundColor: colors.panel2 },
  timePointButtonActive: { borderColor: colors.accent, backgroundColor: colors.accentSoft },
  timePointText: { color: colors.muted, fontSize: 13, fontWeight: "900" },
  timePointTextActive: { color: colors.text },
  watchHint: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 9 },
  ratingSheetActions: { flexDirection: "row", gap: 10, marginTop: 14 },
  ratingGhostButton: { flex: 1, height: 52, borderRadius: 18, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center" },
  ratingGhostText: { color: colors.text, fontWeight: "900" },
  ratingSaveButton: { flex: 1, height: 52, borderRadius: 18, backgroundColor: colors.accent, alignItems: "center", justifyContent: "center" },
  ratingSaveText: { color: colors.text, fontWeight: "900" },
  scoreControl: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 14 },
  scoreStepButton: { width: 46, height: 46, borderRadius: 23, backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center" },
  scoreInput: { flex: 1, height: 50, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel2, color: colors.text, fontSize: 22, fontWeight: "900", textAlign: "center" },
  reviewComposerSection: { marginTop: 46 },
  reviewComposerPanel: { marginHorizontal: 18, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 18 },
  reviewComposerTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  reviewComposerScore: { color: "#ffc24b", fontFamily: "serif", fontSize: 25, fontWeight: "700", marginTop: 3 },
  clearRatingText: { color: colors.muted, fontSize: 12, fontWeight: "900", marginTop: 4 },
  reviewTitleInput: { minHeight: 54, borderBottomWidth: 1, borderBottomColor: colors.line, color: colors.text, fontSize: 18, marginTop: 18 },
  reviewBodyInput: { minHeight: 130, paddingTop: 12, lineHeight: 24 },
  reviewComposerFooter: { marginTop: 18, gap: 14 },
  spoilerCopy: { flexDirection: "row", alignItems: "center", gap: 10 },
  spoilerTitle: { color: colors.text, fontWeight: "900" },
  spoilerBody: { color: colors.muted, fontSize: 12, marginTop: 2 },
  publishReviewButton: { minHeight: 54, borderRadius: 22, backgroundColor: colors.accent, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  publishReviewText: { color: colors.text, fontSize: 16, fontWeight: "900" },
  detailSection: { marginTop: 46 },
  seasonsHeader: { paddingHorizontal: 18, flexDirection: "row", alignItems: "flex-end", gap: 14 },
  seasonsHeaderCopy: { flex: 1, minWidth: 0 },
  seasonsHeaderTitle: { color: colors.text, fontFamily: "serif", fontSize: 34, lineHeight: 39, marginTop: 7 },
  seasonsHeaderAction: { maxWidth: 132, minHeight: 42, paddingBottom: 3, flexDirection: "row", alignItems: "center", justifyContent: "flex-end", gap: 4 },
  seasonsHeaderActionText: { flexShrink: 1, color: colors.muted, fontSize: 12, lineHeight: 16, fontWeight: "900", textAlign: "right" },
  seasonList: { paddingHorizontal: 18, marginTop: 14, gap: 10 },
  seasonCard: { minHeight: 92, borderRadius: 18, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, flexDirection: "row", alignItems: "center", padding: 10, gap: 12 },
  seasonPoster: { width: 48, height: 72, borderRadius: 8, backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center" },
  seasonCopy: { flex: 1, minWidth: 0 },
  seasonName: { color: colors.text, fontSize: 16, fontWeight: "900" },
  seasonMeta: { color: colors.muted, fontSize: 13, fontWeight: "700", marginTop: 4 },
  episodeCardTrailing: { alignItems: "flex-end", justifyContent: "center", gap: 8 },
  episodeOwnRating: { flexDirection: "row", alignItems: "center", gap: 4, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5, backgroundColor: "rgba(255,194,75,0.10)", borderWidth: 1, borderColor: "rgba(255,194,75,0.24)" },
  episodeOwnRatingText: { color: "#ffc24b", fontSize: 12, fontWeight: "900" },
  sourceTabs: { flexDirection: "row", gap: 9, paddingHorizontal: 18, marginTop: 10, flexWrap: "wrap" },
  sourceTab: { minHeight: 42, paddingHorizontal: 14, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, alignItems: "center", justifyContent: "center" },
  sourceTabActive: { borderColor: colors.accent, backgroundColor: "rgba(255,84,57,0.18)" },
  sourceTabDisabled: { opacity: 0.42 },
  sourceTabText: { color: colors.text, fontWeight: "900" },
  ratingGraphControls: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingHorizontal: 18, marginTop: 12 },
  ratingGraphToggle: { minHeight: 42, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 8 },
  ratingGraphToggleActive: { borderColor: colors.accent, backgroundColor: "rgba(255,84,57,0.16)" },
  ratingGraphToggleText: { color: colors.text, fontSize: 13, fontWeight: "900" },
  watchProgressCard: { marginHorizontal: 18, marginTop: 14, borderRadius: 18, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, padding: 14 },
  watchProgressHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 },
  watchProgressLabel: { color: colors.accent, fontSize: 11, fontWeight: "900", letterSpacing: 2, textTransform: "uppercase" },
  watchProgressValue: { color: colors.text, fontSize: 18, fontWeight: "900", marginTop: 4 },
  watchProgressToggle: { minHeight: 38, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel2, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 6 },
  watchProgressToggleActive: { borderColor: colors.accent, backgroundColor: "rgba(255,84,57,0.18)" },
  watchProgressToggleText: { color: colors.muted, fontSize: 12, fontWeight: "900" },
  watchProgressToggleTextActive: { color: colors.text },
  watchProgressTrack: { height: 8, borderRadius: 999, backgroundColor: colors.panel2, overflow: "hidden", marginTop: 12 },
  watchProgressFill: { height: "100%", borderRadius: 999, backgroundColor: colors.accent },
  ratingLegend: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingHorizontal: 18, marginTop: 10 },
  ratingLegendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  ratingLegendDot: { width: 9, height: 9, borderRadius: 5 },
  ratingLegendText: { color: colors.muted, fontSize: 11, fontWeight: "800" },
  fullMatrixScroll: { paddingHorizontal: 18, paddingVertical: 12 },
  fullEpisodeMatrix: { gap: 6 },
  matrixRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  matrixAxisCell: { width: 64, color: colors.muted, fontSize: 12, fontWeight: "900" },
  matrixHeaderCell: { width: 48, textAlign: "center", color: colors.muted, fontSize: 12, fontWeight: "900" },
  matrixEmptyCell: { width: 48, height: 42, borderRadius: 8, backgroundColor: "rgba(255,255,255,0.05)" },
  matrixCell: { width: 48, height: 42, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  matrixCellText: { fontSize: 14, fontWeight: "900" },
  dimmedEpisode: { opacity: 0.38 },
  dimmedEpisodeCard: { opacity: 0.42 },
  mutedBody: { color: colors.muted, fontSize: 13, lineHeight: 20, paddingHorizontal: 18 },
  seasonEpisodeGrid: { paddingHorizontal: 18, paddingVertical: 14, gap: 8 },
  seasonEpisodeCell: { width: 62, height: 54, borderRadius: 9, backgroundColor: "#f5c20b", alignItems: "center", justifyContent: "center" },
  seasonEpisodeCode: { color: "#1d1705", fontSize: 11, fontWeight: "900" },
  seasonEpisodeScore: { color: "#1d1705", fontSize: 18, fontWeight: "900", marginTop: 2 },
  trailerPreview: { marginHorizontal: 18, minHeight: 190, borderRadius: 22, backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center", gap: 8, overflow: "hidden" },
  trailerPreviewText: { color: colors.text, fontSize: 22, fontWeight: "900" },
  trailerPreviewSub: { color: colors.muted, fontSize: 13, fontWeight: "800" },
  galleryGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", marginTop: 14, paddingHorizontal: 18, marginBottom: 28, rowGap: 14 },
  galleryTile: { width: "48%", aspectRatio: 1.35, borderRadius: 16, overflow: "hidden", backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center" },
  galleryScrim: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(0,0,0,0.44)" },
  galleryText: { color: colors.text, fontSize: 14, fontWeight: "900", marginTop: 8 },
  gallerySub: { color: colors.muted, fontSize: 12, marginTop: 2 },
  galleryModal: { flex: 1, backgroundColor: "rgba(0,0,0,0.96)" },
  galleryClose: { position: "absolute", top: 18, right: 18, zIndex: 3, width: 44, height: 44, borderRadius: 22, backgroundColor: "rgba(255,255,255,0.12)", alignItems: "center", justifyContent: "center" },
  gallerySlide: { alignItems: "center", justifyContent: "center", paddingHorizontal: 12 },
  gallerySlideImage: { width: "100%", height: "86%" },
  castGrid: { flexDirection: "row", flexWrap: "wrap", paddingHorizontal: 18, marginTop: 8, rowGap: 28 },
  personCard: { width: "33.33%", minHeight: 142, alignItems: "center", paddingHorizontal: 5 },
  personPhoto: { width: 94, height: 94, borderRadius: 47, backgroundColor: colors.panel2 },
  personName: { color: colors.text, fontSize: 14, fontWeight: "900", marginTop: 10, textAlign: "center" },
  personRole: { color: colors.muted, fontSize: 12, marginTop: 2, textAlign: "center" },
  companyGrid: { flexDirection: "row", flexWrap: "wrap", rowGap: 12, columnGap: 12, paddingHorizontal: 18, marginTop: 8 },
  companyCard: { width: "47.5%", borderRadius: 18, borderWidth: 1, borderColor: colors.line, padding: 10, backgroundColor: colors.panel, alignItems: "center" },
  companyLogo: { width: "100%", height: 82, borderRadius: 12, backgroundColor: "#eeeae2", alignItems: "center", justifyContent: "center" },
  companyLogoImage: { width: "90%", height: "80%" },
  companyInitial: { color: "#161a1b", fontFamily: "serif", fontSize: 30, fontWeight: "700" },
  companyName: { color: colors.text, fontSize: 14, fontWeight: "900", marginTop: 10, textAlign: "center" },
  featureIntro: { color: colors.muted, fontSize: 15, lineHeight: 22, marginHorizontal: 18, marginBottom: 18 },
  featureForm: { marginHorizontal: 18, padding: 16, borderRadius: 22, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, gap: 18 },
  featureField: { gap: 8 },
  featureLabel: { color: colors.text, fontSize: 14, fontWeight: "900" },
  featureChoices: { flexDirection: "row", gap: 8, paddingRight: 10 },
  featureChoice: { minHeight: 38, paddingHorizontal: 12, borderWidth: 1, borderColor: colors.line, borderRadius: 20, backgroundColor: colors.panel2, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 5 },
  featureChoiceActive: { borderColor: colors.accent, backgroundColor: "rgba(255,91,62,.17)" },
  featureChoiceText: { color: colors.muted, fontSize: 12, fontWeight: "800" },
  featureChoiceTextActive: { color: colors.text },
  featurePrimary: { minHeight: 52, marginTop: 3, borderRadius: 18, backgroundColor: colors.accent, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingHorizontal: 18 },
  featurePrimaryText: { color: "#fff", fontSize: 15, fontWeight: "900" },
  featureLink: { marginHorizontal: 18, marginBottom: 18, padding: 16, borderWidth: 1, borderColor: colors.line, borderRadius: 20, backgroundColor: colors.panel, flexDirection: "row", alignItems: "center", gap: 12 },
  featureLinkTitle: { color: colors.text, fontSize: 16, fontWeight: "900" },
  featureLinkBody: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 2 },
  wrappedEntryCard: { marginHorizontal: 18, marginBottom: 18, padding: 14, borderWidth: 1, borderColor: "rgba(255,91,62,.28)", borderRadius: 18, backgroundColor: "rgba(255,91,62,.07)", flexDirection: "row", alignItems: "center", gap: 12 },
  wrappedEntryIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: "rgba(255,91,62,.13)", alignItems: "center", justifyContent: "center" },
  wrappedEntryCopy: { flex: 1, minWidth: 0 },
  wrappedEntryEyebrow: { color: colors.accent, fontSize: 9, fontWeight: "900", letterSpacing: 1.5, textTransform: "uppercase", marginBottom: 3 },
  wrappedEntryTitle: { color: colors.text, fontSize: 15, fontWeight: "900" },
  wrappedEntryBody: { color: colors.muted, fontSize: 11, marginTop: 3 },
  tonightMobileCard: { marginHorizontal: 18, marginTop: 18, padding: 12, borderWidth: 1, borderColor: colors.line, borderRadius: 22, backgroundColor: colors.panel, overflow: "hidden", gap: 8 },
  tonightMobileArt: { width: "100%", aspectRatio: 1.78, borderRadius: 14, backgroundColor: colors.panel2 },
  tonightMobileTitle: { color: colors.text, fontFamily: "serif", fontSize: 30, fontWeight: "700" },
  tonightReason: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  tonightMessage: { color: colors.muted, fontSize: 13, lineHeight: 19, textAlign: "center", paddingHorizontal: 8 },
  featureShelf: { marginTop: 24, marginHorizontal: 18, gap: 8 },
  upNextShelfHead: { minHeight: 34, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  upNextShelfTitle: { color: colors.text, fontFamily: "serif", fontSize: 28, lineHeight: 32, fontWeight: "700" },
  upNextShelfCount: { minWidth: 24, height: 24, borderRadius: 12, overflow: "hidden", backgroundColor: colors.panel2, color: colors.muted, textAlign: "center", lineHeight: 24, fontSize: 11, fontWeight: "900" },
  upNextMobileRow: { minHeight: 78, padding: 8, borderWidth: 1, borderColor: colors.line, borderRadius: 14, backgroundColor: colors.panel, flexDirection: "row", alignItems: "center", gap: 10 },
  upNextMobileArt: { width: 86, height: 60, borderRadius: 9, backgroundColor: colors.panel2 },
  upNextMobileCopy: { flex: 1, minWidth: 0 },
  upNextKicker: { color: colors.accent, fontSize: 9, fontWeight: "900", letterSpacing: 1.3, textTransform: "uppercase" },
  upNextMobileTitle: { color: colors.text, fontSize: 14, fontWeight: "900", marginTop: 1 },
  upNextMobileSubtitle: { color: colors.muted, fontSize: 11, marginTop: 2 },
  upNextMobileMeta: { color: colors.muted, fontSize: 9, marginTop: 3 },
  eveningMobile: { marginHorizontal: 18, marginVertical: 15, padding: 16, borderWidth: 1, borderColor: colors.line, borderRadius: 22, backgroundColor: colors.panel, gap: 12 },
  eveningTitle: { color: colors.text, fontFamily: "serif", fontSize: 30, lineHeight: 34, fontWeight: "700" },
  eveningTotal: { color: colors.text, fontSize: 15, fontWeight: "900", marginTop: 4 },
  eveningQueueRow: { borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 10 },
  wrappedHeader: { marginHorizontal: 18, padding: 18, borderRadius: 22, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line },
  wrappedBack: { alignSelf: "flex-start", minHeight: 32, paddingRight: 10, marginBottom: 16, flexDirection: "row", alignItems: "center", gap: 3 },
  wrappedBackText: { color: colors.text, fontSize: 12, fontWeight: "900" },
  wrappedTitle: { color: colors.text, fontFamily: "serif", fontSize: 43, lineHeight: 47, fontWeight: "700", marginTop: 5 },
  wrappedMobileLine: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 10 },
  wrappedShareButton: { alignSelf: "flex-start", minHeight: 42, marginTop: 16, paddingHorizontal: 15, borderWidth: 1, borderColor: "rgba(255,91,62,.36)", borderRadius: 21, backgroundColor: "rgba(255,91,62,.10)", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  wrappedShareText: { color: colors.text, fontSize: 13, fontWeight: "900" },
  wrappedStatsGrid: { marginHorizontal: 18, marginTop: 12, flexDirection: "row", flexWrap: "wrap", gap: 10 },
  wrappedStatCard: { width: "48%", minHeight: 92, padding: 14, borderRadius: 16, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, justifyContent: "space-between" },
  wrappedStatValue: { color: colors.text, fontFamily: "serif", fontSize: 31, lineHeight: 35, fontWeight: "700" },
  wrappedStatLabel: { color: colors.muted, fontSize: 11, lineHeight: 15, fontWeight: "800" },
  wrappedSectionHead: { marginHorizontal: 18, marginTop: 32, marginBottom: 12 },
  wrappedSectionTitle: { color: colors.text, fontFamily: "serif", fontSize: 31, lineHeight: 35, fontWeight: "700", marginTop: 4 },
  wrappedBars: { gap: 4 },
  wrappedMobileBar: { marginHorizontal: 18, minHeight: 38, flexDirection: "row", alignItems: "center", gap: 8 },
  wrappedCalloutList: { marginHorizontal: 18, marginTop: 22, gap: 10 },
  wrappedMobileCallout: { padding: 14, borderRadius: 15, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line },
  wrappedCalloutLabel: { color: colors.muted, fontSize: 10, fontWeight: "800", textTransform: "uppercase", letterSpacing: .8 },
  wrappedCalloutValue: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "900", marginTop: 5 },
  wrappedHeatHint: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 5 },
  wrappedHeatScroll: { paddingHorizontal: 18, paddingBottom: 8 },
  wrappedHeatWeeks: { flexDirection: "row", gap: 3, padding: 12, borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel },
  wrappedHeatWeek: { gap: 3 },
  wrappedHeatCell: { width: 10, height: 10, borderRadius: 2, backgroundColor: "rgba(255,255,255,.06)" },
  wrappedHeatCellEmpty: { width: 10, height: 10 },
  wrappedHeatCell1: { backgroundColor: "rgba(255,91,62,.28)" },
  wrappedHeatCell2: { backgroundColor: "rgba(255,91,62,.48)" },
  wrappedHeatCell3: { backgroundColor: "rgba(255,91,62,.72)" },
  wrappedHeatCell4: { backgroundColor: colors.accent },
  settingsWrap: { paddingBottom: 20 },
  settingsTabs: { gap: 10, paddingHorizontal: 18, paddingBottom: 12 },
  settingsTab: { minHeight: 42, borderRadius: 22, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 14, alignItems: "center", justifyContent: "center", backgroundColor: colors.panel },
  settingsTabActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  settingsTabText: { color: colors.muted, fontWeight: "900" },
  settingsTabTextActive: { color: colors.text },
  settingsPanel: { marginHorizontal: 18, marginTop: 10, borderRadius: 24, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, padding: 18 },
  settingsTitle: { color: colors.text, fontFamily: "serif", fontSize: 32, marginBottom: 12 },
  settingsBody: { color: colors.muted, fontSize: 15, lineHeight: 23 },
  settingsField: { marginTop: 12 },
  settingsLabel: { color: colors.muted, fontSize: 12, fontWeight: "900", letterSpacing: 1.2, textTransform: "uppercase", marginBottom: 6 },
  settingsInput: { minHeight: 52, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel2, color: colors.text, fontSize: 16, paddingHorizontal: 12 },
  profileMediaRow: { minHeight: 82, borderRadius: 18, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel2, padding: 10, flexDirection: "row", alignItems: "center", gap: 12 },
  profileMediaPreview: { flexShrink: 0, overflow: "hidden", backgroundColor: colors.panel, alignItems: "center", justifyContent: "center" },
  profileMediaAvatar: { width: 62, height: 62, borderRadius: 31 },
  profileMediaBanner: { width: 110, height: 62, borderRadius: 14 },
  profileMediaImage: { width: "100%", height: "100%" },
  profileMediaButton: { flex: 1, minWidth: 0, minHeight: 48, borderRadius: 16, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, paddingHorizontal: 12 },
  profileMediaButtonText: { color: colors.text, flexShrink: 1, fontSize: 14, fontWeight: "900", textAlign: "center" },
  settingsTextArea: { minHeight: 112, paddingTop: 12, textAlignVertical: "top" },
  settingsSave: { height: 56, borderRadius: 20, backgroundColor: colors.accent, alignItems: "center", justifyContent: "center", marginTop: 18 },
  settingsSaveText: { color: colors.text, fontSize: 17, fontWeight: "900" },
  settingsGhost: { minHeight: 52, borderRadius: 18, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center", marginTop: 16 },
  settingsGhostText: { color: colors.text, fontWeight: "900" },
  settingsDanger: { minHeight: 52, borderRadius: 18, borderWidth: 1, borderColor: "rgba(255,77,77,0.36)", backgroundColor: "rgba(255,77,77,0.10)", alignItems: "center", justifyContent: "center", marginTop: 12 },
  settingsDangerText: { color: colors.danger, fontWeight: "900" },
  settingsError: { color: colors.danger, fontSize: 14, fontWeight: "800", lineHeight: 20, marginTop: 12 },
  integrationBox: { marginTop: 16, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 16 },
  integrationLabel: { color: colors.muted, fontSize: 12, fontWeight: "900", letterSpacing: 1.2, textTransform: "uppercase" },
  integrationValue: { color: colors.text, fontSize: 22, fontWeight: "900", marginTop: 4, marginBottom: 8 },
  securityButtonRow: { flexDirection: "row", gap: 8, marginTop: 10 },
  securitySmallButton: { flex: 1, minHeight: 48, borderRadius: 16, backgroundColor: colors.accent, alignItems: "center", justifyContent: "center", paddingHorizontal: 10 },
  securitySmallButtonGhost: { flex: 1, minHeight: 48, borderRadius: 16, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center", paddingHorizontal: 10 },
  securitySmallButtonText: { color: colors.text, fontSize: 14, fontWeight: "900", textAlign: "center" },
  securityFactorRow: { minHeight: 72, borderRadius: 16, borderWidth: 1, borderColor: "rgba(110,231,168,0.36)", backgroundColor: "rgba(110,231,168,0.08)", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, padding: 12, marginTop: 10 },
  securityFactorCopy: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 10 },
  securityFactorTitle: { color: colors.text, fontSize: 14, fontWeight: "900" },
  securityFactorSub: { color: colors.muted, fontSize: 12, marginTop: 2 },
  securityRemoveButton: { minHeight: 38, borderRadius: 14, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center", paddingHorizontal: 12 },
  securityRemoveText: { color: colors.text, fontSize: 13, fontWeight: "900" },
  securityEnrollBox: { marginTop: 12, gap: 10 },
  securitySecretText: { color: colors.text, backgroundColor: colors.panel2, borderRadius: 14, borderWidth: 1, borderColor: colors.line, padding: 12, fontSize: 14, fontWeight: "900", lineHeight: 20 },
  privacyRow: { minHeight: 56, borderBottomWidth: 1, borderBottomColor: colors.line, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  privacyLabel: { color: colors.text, fontSize: 16, fontWeight: "800", textTransform: "capitalize", flex: 1 },
  privacyValue: { color: colors.accent, fontSize: 14, fontWeight: "900", textTransform: "capitalize" },
  toggleRow: { minHeight: 58, borderBottomWidth: 1, borderBottomColor: colors.line, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }
});
