import type { PickerAnchor } from "../components";
import type { MediaKind, MediaSummary } from "../types";
import type { SeriesViewingSummary } from "../viewing-passes";

export type PickerState = { title: string; value: string; options: Array<{ value: string; label: string }>; multiValues?: string[]; anchor?: PickerAnchor; onPick: (value: string) => void; onApply?: (values: string[]) => void } | null;
export type HomeSection = { title: string; kicker: string; items: MediaSummary[] };
export type ProgressCounts = { planned: number; watching: number; completed: number; paused: number; dropped: number; favorites: number };
export type MediaKindCounts = { total: number; movie: number; show: number };
export type Profile = { id: string; username: string | null; display_name: string | null; avatar_url: string | null; banner_url: string | null; bio: string | null; region: string | null; created_at?: string | null };
export type ProfileImageSelection = { uri: string; fileName?: string | null; mimeType?: string | null; changed: boolean };
export type MfaState = { required: boolean; factorId?: string; challengeId?: string; code: string; error?: string };
export type WatchTimePoint = "start" | "end";
export type WatchDateMode = "now" | "release" | "unknown" | "custom";
export type WatchLogValues = { mode: WatchDateMode; date?: string; time?: string; timePoint: WatchTimePoint };
export type LibraryFilter = "all" | "planned" | "watching" | "completed" | "paused" | "dropped" | "favorites" | "lists";
export type ListGroup = "none" | "collections";
export type ListSort = "none" | "title_asc" | "title_desc" | "release_desc" | "release_asc" | "added_desc" | "added_asc" | "list_order";
export type ActionRefreshReason = "profile" | "list" | "watch" | "rating";
export type CalendarMode = "upcoming" | "watched";
export type CalendarView = "month" | "week";
export type ProfilePanel = "journal" | "reviews" | "history" | "statistics";
export type ProfileView = "profile" | "recommendations" | "settings" | "journal" | "history" | "reviews" | "statistics" | "wrapped" | "notifications";
export type FeatureView = "tonight" | "up-next" | null;
export type HistoryFilter = "all" | "movies" | "episodes";
export type CalendarEvent = { id: string; date: string; title: string; subtitle: string; artwork: string | null; item?: MediaSummary | null; href?: string | null; episodeTarget?: EpisodeTarget | null };
export type EpisodeTarget = { episodeId?: number; show: MediaSummary; seasonNumber: number; episodeNumber: number; title?: string | null; overview?: string | null; airDate?: string | null; artwork?: string | null; runtime?: number | null; voteAverage?: number | null };
export type SeasonTarget = { show: MediaSummary; season: DetailSeason };
export type SeriesEpisodesTarget = { show: MediaSummary; seasons: DetailSeason[] };
export type EntityTarget =
  | { type: "person"; id: number; name: string; subtitle?: string | null; imagePath?: string | null }
  | { type: "company"; id: number; name: string; subtitle?: string | null; imagePath?: string | null };
export type UserList = { id: string; name: string; description: string | null; visibility: string | null; cover_url?: string | null; count: number; posters: string[] };
export type ReviewItem = { id: string; title: string; body: string; created_at: string; updated_at?: string | null; userId?: string | null; ratingId?: string | null; containsSpoilers?: boolean | null; isPrivate?: boolean | null; kind: MediaKind; targetLabel?: "season" | "episode"; targetMeta?: string | null; mediaTitle: string; artwork: string | null; score?: number | null; item?: MediaSummary | null; seasonTarget?: SeasonTarget | null; episodeTarget?: EpisodeTarget | null };
export type TrackedStatus = "completed" | "watching" | "planned" | "paused" | "dropped";
export type GenreStat = { name: string; total: number; statuses: Record<TrackedStatus, number>; items: Array<{ status: TrackedStatus; item: MediaSummary }> };
export type HistoryItem = {
  id: string;
  date: string;
  dateKey: string;
  dateTitle: string;
  dateSubtitle: string;
  timeLabel: string;
  title: string;
  subtitle: string;
  metaLabel: string;
  artwork: string | null;
  rating?: number | null;
  rewatchNumber?: number;
  item?: MediaSummary | null;
  episodeTarget?: EpisodeTarget | null;
};
export type ListMembership = UserList & { contains: boolean };
export type SettingsTab = "profile" | "privacy" | "security" | "notifications" | "integrations";
export type DetailPerson = { id?: number; name: string; character?: string; job?: string; profile_path?: string | null };
export type DetailCompany = { id?: number; name: string; logo_path?: string | null };
export type DetailVideo = { key?: string; name?: string; type?: string; official?: boolean };
export type DetailImage = { file_path?: string; filePath?: string };
export type DetailSeason = { id?: number; seasonNumber: number; name: string; overview?: string | null; posterPath?: string | null; airDate?: string | null; episodeCount?: number | null };
export type DetailData = {
  dbId: number | null;
  overview: string | null;
  tagline: string | null;
  releaseDate: string | null;
  endDate: string | null;
  genres: Array<{ id?: number; name: string }>;
  voteAverage: number | null;
  runtime: number | null;
  originalLanguage: string | null;
  status: string | null;
  userRating: number | null;
  communityRating: number | null;
  externalRatings: Array<{ label: string; value: string }>;
  pendingExternalRatingSources?: string[];
  progressStatus: string | null;
  seriesProgress?: SeriesViewingSummary | null;
  watched: boolean;
  lastWatchedAt?: string | null;
  favorite: boolean;
  lists: ListMembership[];
  cast: DetailPerson[];
  crew: DetailPerson[];
  companies: DetailCompany[];
  videos: DetailVideo[];
  images: DetailImage[];
  seasons: DetailSeason[];
  reviews: ReviewItem[];
  myReview: ReviewItem | null;
  collectionName: string | null;
  collection: MediaSummary[];
  recommendations: MediaSummary[];
};
export type ProfileData = {
  followers: number;
  following: number;
  tracked: number;
  trackedLibraryTitles: number;
  watchEvents: number;
  screenTimeHours: number;
  historyUniqueTitles: number;
  averageRating: string;
  reviewCount: number;
  listCount: number;
  history: HistoryItem[];
  reviews: ReviewItem[];
  favorites: MediaSummary[];
  lists: UserList[];
  progressGroups: Array<{ key: "completed" | "active" | "dropped"; label: string; count: number; posters: string[] }>;
  currentStreak: number;
  longestStreak: number;
  currentlyWatching: MediaSummary[];
  genreStats: GenreStat[];
};
